### ISSUE TITLE
Travis CI Docker Compose Version

### ISSUE THREAD

**Issue by derks** [datafolklabs/cement#687]
Currently we are pinning Docker Compose version to 2.17.3 in Travis CI:

*.travis.yml*

```
matrix:
  include:
    - python: "3.12"
      dist: "jammy"
      sudo: true
      env:
        - DOCKER_COMPOSE_VERSION=v2.17.3
        - SMTP_HOST=localhost
        - SMTP_PORT=1025
```

I can not recall when/why this was pinned. Currently I'm running 2.27.0 (macOS). Should update this to keep current.
